### ISSUE TITLE
Update to ImgLib2 v5 API

### ISSUE THREAD

**Issue by ctrueden** [imglib/imglib2-tutorials#5]
The ImgLib2 v5 API has some breaking changes, which need to be taken into account in these tutorials. I did most of the work already; see https://github.com/imglib/imglib2-tutorials/compare/imglib2-v5. But the `LifeForm` class of the game still needs updating.

**Comment by tpietzsch** [comment]
Finally done...

**Comment by StephanPreibisch** [comment]
Thanks a lot @tpietzsch ... I could have just looked at it over the weekend.
